- hosts: webservers
  gather_facts: true
  become: true

  roles:
    - role: letsencrypt
      vars:
       letsencrypt_email: "{{ email_letsencrypt }}"
       main_domain_name: "{{ main_domain }}" 

       all_domain_names:
           - "{{ main_domain }}"
       
       deploy_sample_html: true
