- name: create folder {{ folder_web }}
  file:
    path: /var/www/{{ main_domain_name }}/{{ folder_web }}/
    state: directory
    mode: '0755'
    

- name: install git
  apt:
    name: git

- name: Deploy sample html file 
  git:
    repo: '{{ github_repo }}'
    dest: /var/www/{{ main_domain_name }}/{{ folder_web }}/
    force: yes

- name: copy configuration file to {{ folder_web }}
  template:
    src: config.php
    dest: /var/www/{{ main_domain_name }}/{{ folder_web }}/


- name: copy dump SQL file to tmp
  template:
    src: dump.sql
    dest: /var/tmp/


- name: Run SQL commands to create database {{ pesbuk_db_name }}
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: present
        



- name: Deploy Database Dump SQL to remote server {{ main_domain }} 
  mysql_db:
        login_host: "{{ pesbuk_db_hostname }}"
        login_password: "{{ pesbuk_db_password }}"
        login_user: "{{ pesbuk_db_user }}"
        login_port: "3306"
        name: "{{ pesbuk_db_name }}"
        state: import
        target: "{{ target_dump }}"

